In [1]:
## can we find the GT values in our product catalogue?

import pandas as pd

df_cat = pd.read_excel('data\Mattsco Product Parsed.Marty.12.19.24.xlsx')
df_gt = pd.read_excel('data\Mattsco GT (dupes removed).xlsx')

print('df_cat size: ', len(df_cat))
print('df_gt size: ', len(df_gt))

df_cat size:  28192
df_gt size:  571

In [2]:
df_gt.columns

Index(['Customer's Inbound RFQ Description', 'Selected Part Number',
       'Descrip from Prod Cat'],
      dtype='object')

In [3]:
# find product ID for each one...

df_cat.columns

Index(['Product Code', 'Description', 'Category', 'Type', 'Primary Size',
       'Reducing Size', 'Length', 'Material Name', 'Material Specification',
       'Material Grade', 'Pressure Class', 'Primary Schedule',
       'Reducing Schedule', 'Manufacturing Process', 'End Finish',
       'End Connections', 'Trim', 'Miscellaneous', 'confidence',
       'original_text', 'Primary Wall', 'Reducing Wall', 'Wall Thickness',
       'max', 'od', 'id', 'wall', 'message', 'Note', 'error', '{error',
       'For example you might provide something like', 'first_end',
       'second_end', 'end1', 'end2',
       'For example a description might look like',
       'To proceed I would need an actual component description to extract data according to the provided schema. This could be something like',
       'For example you could provide a description like'],
      dtype='object')

In [4]:
# Find matches and create new dataframe
df_new = df_gt[df_gt['Selected Part Number'].isin(df_cat['Product Code'])]

# Get count of matches
match_count = len(df_new)

print(f"Number of matching items: {match_count}")

Number of matching items: 571

In [5]:
# Check for duplicates
duplicates = df_gt['Selected Part Number'].duplicated().sum()
print(f"Duplicates in df_gt: {duplicates}")

# If no duplicates in df_gt, check matches per part number
test_merge = pd.merge(df_gt, df_cat,
                     left_on='Selected Part Number',
                     right_on='Product Code',
                     how='left')
                     
print(test_merge.groupby('Selected Part Number').size().sort_values(ascending=False).head())

# To keep only first match:
merged_df = pd.merge(df_gt, df_cat,
                    left_on='Selected Part Number',
                    right_on='Product Code',
                    how='left').drop_duplicates(subset=['Selected Part Number'])

print('len of merged: ', len(merged_df))

Duplicates in df_gt: 151
Selected Part Number
FWN03080110    8
FWN011001S     8
FWN06020116    8
IPS4010ST      8
M3T4005360     8
dtype: int64
len of merged:  420

In [6]:
# select 100 randos...

final_df = merged_df.sample(n=100, random_state=42)  # Use random_state for reproducibility

print('len of final: ', len(final_df))

final_df.columns

len of final:  100

Index(['Customer's Inbound RFQ Description', 'Selected Part Number',
       'Descrip from Prod Cat', 'Product Code', 'Description', 'Category',
       'Type', 'Primary Size', 'Reducing Size', 'Length', 'Material Name',
       'Material Specification', 'Material Grade', 'Pressure Class',
       'Primary Schedule', 'Reducing Schedule', 'Manufacturing Process',
       'End Finish', 'End Connections', 'Trim', 'Miscellaneous', 'confidence',
       'original_text', 'Primary Wall', 'Reducing Wall', 'Wall Thickness',
       'max', 'od', 'id', 'wall', 'message', 'Note', 'error', '{error',
       'For example you might provide something like', 'first_end',
       'second_end', 'end1', 'end2',
       'For example a description might look like',
       'To proceed I would need an actual component description to extract data according to the provided schema. This could be something like',
       'For example you could provide a description like'],
      dtype='object')

In [7]:
# Columns to add _GT suffix
gt_suffix_cols = ['Category', 'Type', 'Primary Size', 'Reducing Size', 'Length', 
                 'Material Name', 'Material Specification', 'Material Grade', 
                 'Pressure Class', 'Primary Schedule', 'Reducing Schedule', 
                 'Manufacturing Process', 'End Finish', 'End Connections', 'Trim', 
                 'Miscellaneous', 'confidence', 'original_text', 'Primary Wall',
                 'Reducing Wall', 'Wall Thickness', 'max', 'od', 'id', 'wall']

# Columns to drop
drop_cols = ['message', 'Note', 'error', '{error', 
           'For example you might provide something like',
           'first_end', 'second_end', 'end1', 'end2',
           'For example a description might look like',
           'To proceed I would need an actual component description to extract data according to the provided schema. This could be something like',
           'For example you could provide a description like']

# Rename columns with _GT suffix
final_df_new = final_df.rename(columns={col: f"{col}_GT" for col in gt_suffix_cols})

# Drop unwanted columns
final_df_new = final_df_new.drop(columns=[col for col in drop_cols if col in final_df.columns])

final_df_new.columns

Index(['Customer's Inbound RFQ Description', 'Selected Part Number',
       'Descrip from Prod Cat', 'Product Code', 'Description', 'Category_GT',
       'Type_GT', 'Primary Size_GT', 'Reducing Size_GT', 'Length_GT',
       'Material Name_GT', 'Material Specification_GT', 'Material Grade_GT',
       'Pressure Class_GT', 'Primary Schedule_GT', 'Reducing Schedule_GT',
       'Manufacturing Process_GT', 'End Finish_GT', 'End Connections_GT',
       'Trim_GT', 'Miscellaneous_GT', 'confidence_GT', 'original_text_GT',
       'Primary Wall_GT', 'Reducing Wall_GT', 'Wall Thickness_GT', 'max_GT',
       'od_GT', 'id_GT', 'wall_GT'],
      dtype='object')

In [9]:
## now send to claude for GT attribute parsing

final_df_new

,Customer's Inbound RFQ Description,Selected Part Number,Descrip from Prod Cat,Product Code,Description,Category_GT,Type_GT,Primary Size_GT,Reducing Size_GT,Length_GT,...,Miscellaneous_GT,confidence_GT,original_text_GT,Primary Wall_GT,Reducing Wall_GT,Wall Thickness_GT,max_GT,od_GT,id_GT,wall_GT
418,"3"" X 4"" Sch. Std Wall Concentric Reducer A234 ...",KWCO040030SSKB,"4"" x 3"" STD CONCENTRIC WELD REDUCER, SA234-WPB",KWCO040030SSKB,"4"" x 3"" STD CONCENTRIC WELD REDUCER, SA234-WPB",FITTING,CONCENTRIC REDUCER,4.0,3,NaN,...,NaN,0.9,4\\ x 3\\ STD CONCENTRIC WELD REDUCER SA234-WPB,NaN,NaN,NaN,NaN,NaN,NaN,NaN
912,"11100566-FLG,WN,RF,12,150#,XH-SA-105N",IFWN011201XNA,"12"" 150# RF WELD NECK FLANGE XH BORE, SA105N",IFWN011201XNA,"12"" 150# RF WELD NECK FLANGE XH BORE, SA105N",FLANGE,WELD NECK,12.0,NaN,NaN,...,NaN,0.9,12\\ 150# RF WELD NECK FLANGE XH BORE SA105N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,"H29984 ELBOW,4"",45-WELDED,LR,BW,S10S,ASTM A403",IWL9404001,"4"" S-10 LR 90° WELD ELL, SA403-WP304L",IWL9404001,"4"" S-10 LR 90° WELD ELL, SA403-WP304L",FITTING,ELBOW 90 LONG RADIUS,4.0,NaN,NaN,...,NaN,0.9,4\\ S-10 LR 90° WELD ELL SA403-WP304L,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1008,"10-150-FLG,WN,RF,10,150#,STD-SA-105",FWN011001S,"10"" 150# RF WELD NECK FLANGE STD BORE, SA105N-FGP",FWN011001S,"10"" 150# RF WELD NECK FLANGE STD BORE, SA105N-FGP",FLANGE,WELD NECK,10.0,NaN,NaN,...,FGP,0.9,10\\ 150# RF WELD NECK FLANGE STD BORE SA105N-FGP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1134,"HB5023 FL1,150,SW,RF,SCHXS,ASTM A105N",IFSW010101X,"1"" 150# RF SOCKET WELD FLANGE XH BORE, SA105",IFSW010101X,"1"" 150# RF SOCKET WELD FLANGE XH BORE, SA105",FLANGE,SOCKET WELD,1.0,NaN,NaN,...,XH BORE,0.9,1\\ 150# RF SOCKET WELD FLANGE XH BORE SA105,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,"8-XA106BS-PIPE,SMLS,8,XH (S80)",PA080XH,"8"" XH .500w BLK QUAD STENCILED SA106-B SEAMLES...",PA080XH,"8"" XH .500w BLK QUAD STENCILED SA106-B SEAMLES...",PIPE,SEAMLESS,8.0,NaN,NaN,...,QUAD STENCILED,0.9,8\\ XH .500w BLK QUAD STENCILED SA106-B SEAMLE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,"11100835-FLG,WN,RF,8,600#,S120",FWN06080112,"8"" 600# RF WELD NECK FLANGE S-120 BORE, SA105N...",FWN06080112,"8"" 600# RF WELD NECK FLANGE S-120 BORE, SA105N...",FLANGE,WELD NECK,8.0,NaN,NaN,...,S-120 BORE,0.9,8\\ 600# RF WELD NECK FLANGE S-120 BORE SA105N...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
784,"2"" XXS LR WN 90 DEG. A234WPB",KWL9020XX,"2"" XXH LR 90° WELD ELL, SA234-WPB",KWL9020XX,"2"" XXH LR 90° WELD ELL, SA234-WPB",FITTING,LONG RADIUS 90 ELBOW,2.0,NaN,NaN,...,NaN,0.9,2\\ XXH LR 90° WELD ELL SA234-WPB,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1102,"1-160A106BS-PIPE,SMLS,1,S160",IPA01016K,"1"" S-160 .250W BLK SA106-B SEAMLESS PIPE",IPA01016K,"1"" S-160 .250W BLK SA106-B SEAMLESS PIPE",PIPE,SEAMLESS,1.0,NaN,NaN,...,.250W,0.9,1\\ S-160 .250W BLK SA106-B SEAMLESS PIPE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
990,"12700321-PIPE,SMLS,10,S160-SA-106B",IPA10016TM,"10"" S-160 1.125WA53/SA106-B SMLS PIPE",IPA10016TM,"10"" S-160 1.125WA53/SA106-B SMLS PIPE",PIPE,SMLS PIPE,10.0,NaN,NaN,...,1.125WA53,0.9,10\\ S-160 1.125WA53/SA106-B SMLS PIPE,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# send to claude

import json
from datetime import datetime
from time import sleep
import anthropic
import pandas as pd
from time import perf_counter
from PromptManager import PromptManager
from EnhancedDataCleanser import DataCleanser
from dotenv import load_dotenv

load_dotenv()

cleanser = DataCleanser(
        default_uppercase=True,
        measurement_standardization=True,
        fraction_conversion=True
    )

In [12]:
# load the prompt
ATTRIBUTE_PROMPT = PromptManager.get_prompt("Classifier-Detailed-Mini-12.18.24 Prompt.txt")
ATTRIBUTE_PROMPT

'12.18.24 Prompt\n\nROLE: Extract structured data from industrial component descriptions using exact schema provided. Return only JSON result without commentary.\n\nOUTPUT SCHEMA:\n{\n  "category": "pipe"|"valve"|"fitting"|"flange"|"gasket"|"fastener",\n  "type": <string>,\n  "primary_size": <number>,\n  "reducing_size": <number or null>,\n  "length": <number or null>,\n  "material_name": <string or null>,\n  "material_specification": <string or null>,\n  "material_grade": <string or null>,\n  "pressure_class": <string or null>,\n  "primary_schedule": <string or null>,\n  "reducing_schedule": <string or null>,\n  "manufacturing_process": <string or null>,\n  "end_finish": <string or null>,\n  "end_connections": <string or null>,\n  "trim": <string or null>,\n  "miscellaneous": <string or null>,\n  "confidence": <float>,\n  "original_text": <string>\n}\n\n1. CATEGORY DETERMINATION\nPIPE: \n- Keywords: PIPE, LENGTH, FT\n- Must have: size + (schedule|wall thickness)\n- Common formats: [size] [schedule] [material] [length]\n\nVALVE:\n- Keywords: BALL, GATE, GLOBE, CHECK, BV, GV\n- Must have: size + type\n- Common formats: [size] [class] [type] [material] [ends]\n\nFITTING:\n- Keywords: ELL, TEE, RED, CAP, *LET, COUPLING\n- Must have: size + type\n- Reducing items: Include primary and reducing size\n\nFLANGE:\n- Keywords: FLG, RF, FF, RTJ, WN, SO, LJ\n- Must have: size + type + pressure class\n- Common formats: [size] [class] [face] [type]\n\nGASKET:\n- Keywords: GSK, RTJ, SPIRAL, RING\n- Must have: size + type + (material|style)\n- Common formats: [size] [class] [type] [material]\n\nFASTENER:\n- Keywords: BOLT, NUT, STUD, THREADED\n- Must have: size + length (if stud/bolt)\n- Common formats: [size] [material] [length] [grade]\n\n2. TYPE CLASSIFICATION\n\nPIPE TYPES:\n- Base: PIPE\n- Modifiers: SMLS, ERW, DSAW, LSAW\n\nVALVE TYPES:\nBase patterns:\n- BALL → ball_valve\n- GATE → gate_valve\n- GLOBE → globe_valve\n- CHECK → check_valve\nModifiers:\n- 2PC, 3PC → piece_count\n- FP → full_port\n- RP → regular_port\n\nFITTING TYPES:\nElbows:\n- [LR|SR] [angle] [ELBOW|ELL]\n- Angles: 45, 90, 180\n\nReducers:\n- [CONC|ECC|CR|ER] RED*\n- CONC = concentric_reducer\n- ECC = eccentric_reducer\n\nTees/Crosses:\n- [RED|STR] [TEE|CROSS]\n- RED = reducing_tee/cross\n\nO-lets:\n- WOL → weldolet\n- SOL → sockolet\n- TOL → threadolet\n- EOL → elbolet\n- LOL → latrolet\n\nOthers:\n- CAP, COUPLING, UNION\n- HFC → half_coupling\n- FC → full_coupling\n\nFLANGE TYPES:\nFace patterns:\n- RF → raised_face\n- FF → flat_face\n- RTJ → ring_joint\n\nBase types:\n- WN → weld_neck\n- SO → slip_on\n- SW → socket_weld\n- TH → threaded\n- LJ → lap_joint\n- BL → blind\n\nGASKET TYPES:\n- SW* → spiral_wound\n- RTJ → ring_joint_[oval|octagonal]\n- FF → full_face\n- RF → raised_face\n\n3. ATTRIBUTE EXTRACTION\n\nSIZE PATTERNS:\n- Primary: \\d+"\\s|\\d+IN|\\d+MM\n- Reducing: \\d+\\s*[xX]\\s*\\d+\n- Fractions: \\d+\\s*\\d+\\/\\d+\nConvert all to decimal numbers\n\nMATERIAL NAMES:\nCS → carbon_steel:\n- Keywords: CS, WPB, LCB\n- Specs: A105, A216, A234\n\nSS → stainless_steel:\n- Grades: 304*, 316*, 321*\n- Specs: A182, A351, A403\n\nHY → high_yield:\n- Grades: WPHY*\n- Specs: A694, MSS SP-75\n\nSCHEDULES:\nStandard:\n- STD → standard\n- XS → extra_strong\n- XXS → double_extra_strong\n- SCH[number] → schedule_[number]\n\nEND CONNECTIONS:\n- BW → butt_weld\n- SW → socket_weld\n- THD → threaded\n- FLG → flanged\n- PE → plain_end\nMultiple allowed: "BW X FLG"\n\n4. CONFIDENCE SCORING\n\n1.0: All required fields + category-specific validations pass\n0.9: All required fields + minor missing optional fields\n0.8: All required fields but some uncertainty\n0.7: Missing some optional fields\n0.6: Missing non-critical required fields\n0.5: Category uncertain or conflicting patterns\n\nRequired by Category:\nPIPE: size, schedule/wall, material\nVALVE: size, type, class\nFITTING: size(s), type\nFLANGE: size, type, class, face\nGASKET: size, type, material/style\nFASTENER: size, length (if stud/bolt)\n\n5. VALIDATION RULES\n\nSize Ranges:\nPIPE: 1/8" - 72"\nVALVE: 1/4" - 48"\nFITTING: 1/8" - 48"\nFLANGE: 1/2" - 48"\nGASKET: 1/2" - 48"\nFASTENER: 1/4" - 4"\n\nPressure Classes:\nStandard: 150, 300, 600, 900, 1500, 2500\nConversion: 3M = 3000, 6M = 6000\nValidate against type limitations\n\nEnd Connection Limits:\nSW: ≤ 4"\nTHD: ≤ 4"\nBW: ≥ 2"\n\nMaterial Compatibility:\nValidate material_name + specification + grade combinations\nExample: SS + A182 + F304L = valid'

In [13]:

# Set up your Anthropics client
client = anthropic.Anthropic(
    api_key="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"
)

In [14]:

# make attributes from Claude

outlist = []

for i, row in final_df_new.iterrows():

    start_time = perf_counter()

    gt_desc = row["Descrip from Prod Cat"]
    inc_rfq_raw = row["Customer's Inbound RFQ Description"]
    inc_rfq = cleanser.clean_data(inc_rfq_raw)

    # Send the request
    message = client.beta.prompt_caching.messages.create(
        model="claude-3-5-sonnet-20241022",
        max_tokens=4096,
        messages=[
            {
                "role": "user",
                "content": ATTRIBUTE_PROMPT + f"\n\n{i}. {inc_rfq}"
            }
        ]
    )
    
    # Print raw response (for debugging)
    raw_response = message.content[0].text
    #print(f"Raw response for line {i}: {raw_response}")

    r = json.loads(raw_response)

    # grab values
    category = r.get('category')
    type = r.get('type')
    primary_size = r.get('primary_size')
    reducing_size = r.get('reducing_size')
    length = r.get('length')
    material_name = r.get('material_name')
    material_specification = r.get('material_specification')
    material_grade = r.get('material_grade')
    pressure_class = r.get('pressure_class')
    primary_schedule = r.get('primary_schedule')
    reducing_schedule = r.get('reducing_schedule')
    manufacturing_process = r.get('manufacturing_process')
    end_finish = r.get('end_finish')
    end_connections = r.get('end_connections')
    trim = r.get('trim')
    miscellaneous = r.get('miscellaneous')
    confidence = r.get('confidence')
    original_text = r.get('original_text')

    outlist.append([i,start_time,gt_desc, inc_rfq_raw, inc_rfq, category, type, primary_size, reducing_size, length, material_name, material_specification,material_grade, pressure_class, primary_schedule, reducing_schedule, manufacturing_process, end_finish, end_connections, trim, miscellaneous, confidence, original_text])

    print('complete: ', i,r)

cols = ['i','start_time','gt_desc' ,'inc_rfq_raw', 'inc_rfq', 'category', 'type', 'primary_size', 'reducing_size', 'length', 'material_name', 'material_specification','material_grade', 'pressure_class', 'primary_schedule', 'reducing_schedule', 'manufacturing_process', 'end_finish', 'end_connections', trim, 'miscellaneous', 'confidence', 'original_text']
df_out = pd.DataFrame(data=outlist, columns=cols)

complete:  418 {'category': 'fitting', 'type': 'concentric_reducer', 'primary_size': 3.0, 'reducing_size': 4.0, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A234', 'material_grade': 'WPB', 'pressure_class': None, 'primary_schedule': 'standard', 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '3" X 4" SCH. STD WALL CONCENTRIC REDUCER A234 FR. WPB'}
complete:  912 {'category': 'flange', 'type': 'weld_neck', 'primary_size': 12, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A105', 'material_grade': 'N', 'pressure_class': '150', 'primary_schedule': 'XH', 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': 'raised_face', 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 1.0, 'original_text': '11100566-FLG,WN,RF,12,150 ,XH-SA-105N'}
complete:  494 {'category': 'fitting', 'type': '45_degree_long_radius_elbow', 'primary_size': 4, 'reducing_size': None, 'length': None, 'material_name': 'stainless_steel', 'material_specification': 'ASTM A403', 'material_grade': 'S10S', 'pressure_class': None, 'primary_schedule': None, 'reducing_schedule': None, 'manufacturing_process': 'welded', 'end_finish': None, 'end_connections': 'butt_weld', 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': 'H29984 ELBOW,4",45-WELDED,LR,BW,S10S,ASTM A403'}
complete:  1008 {'category': 'flange', 'type': 'weld_neck', 'primary_size': 10, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A105', 'material_grade': None, 'pressure_class': '150', 'primary_schedule': 'standard', 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': 'raised_face', 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '10-150-FLG,WN,RF,10,150 ,STD-SA-105'}
complete:  1134 {'category': 'flange', 'type': 'slip_on', 'primary_size': 1.0, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A105', 'material_grade': 'N', 'pressure_class': '150', 'primary_schedule': 'XS', 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': 'raised_face', 'end_connections': 'socket_weld', 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': 'HB5023 FL1,150,SW,RF,SCHXS,ASTM A105N'}
complete:  210 {'category': 'fitting', 'type': 'concentric_reducer', 'primary_size': 6, 'reducing_size': 5, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'SA-234', 'material_grade': 'WPB', 'pressure_class': None, 'primary_schedule': '160', 'reducing_schedule': '160', 'manufacturing_process': None, 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': 'CONC RED,6X5,S160-CONC RED,6X5,S160-SA-234-WPB'}
complete:  386 {'category': 'pipe', 'type': 'seamless_pipe', 'primary_size': 4, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A106', 'material_grade': 'B', 'pressure_class': None, 'primary_schedule': 'XXH', 'reducing_schedule': None, 'manufacturing_process': 'seamless', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '4-XX106B-PIPE,SMLS,4,XXH-SA-106B'}
complete:  400 {'category': 'fitting', 'type': 'long_radius_45_elbow', 'primary_size': 4.0, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'SA-234', 'material_grade': 'WPB', 'pressure_class': None, 'primary_schedule': 'XH', 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '4-LR45X-ELBOW,LR45,4,XH (S80)-SA-234-WPB'}
complete:  84 {'category': 'pipe', 'type': 'seamless_pipe', 'primary_size': 8, 'reducing_size': None, 'length': None, 'material_name': None, 'material_specification': None, 'material_grade': None, 'pressure_class': None, 'primary_schedule': '60', 'reducing_schedule': None, 'manufacturing_process': 'smls', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.8, 'original_text': '12700629-PIPE,SMLS,8,S60'}
complete:  206 {'category': 'fitting', 'type': 'concentric_reducer', 'primary_size': 6, 'reducing_size': 5, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'SA-234', 'material_grade': 'WPB', 'pressure_class': None, 'primary_schedule': 'XXH', 'reducing_schedule': 'XXH', 'manufacturing_process': None, 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': 'CONC RED,6X5,XXH-MATL: SA-234-WPB'}
complete:  196 {'category': 'pipe', 'type': 'seamless_pipe', 'primary_size': 6, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A106', 'material_grade': 'B', 'pressure_class': None, 'primary_schedule': 'XH', 'reducing_schedule': None, 'manufacturing_process': 'SMLS', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '6-XA106BS-PIPE,SMLS,6,XH (S80)-SA-106B'}
complete:  272 {'category': 'fitting', 'type': 'long_radius_45_elbow', 'primary_size': 6, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'SA234', 'material_grade': 'WPB', 'pressure_class': None, 'primary_schedule': '120', 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '15000222-ELBOW,LR45,6,S120-SA-234-WPB'}
complete:  1004 {'category': 'flange', 'type': 'weld_neck', 'primary_size': 10, 'reducing_size': None, 'length': 13, 'material_name': None, 'material_specification': None, 'material_grade': None, 'pressure_class': '300', 'primary_schedule': None, 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': 'raised_face', 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.8, 'original_text': 'FLG,LWN,RF,10,300 ,13 INCHLG-FLG,LWN,RF,10,300 ,13 INCHLG'}
complete:  252 {'category': 'pipe', 'type': 'smls_pipe', 'primary_size': 6, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A106', 'material_grade': 'B', 'pressure_class': None, 'primary_schedule': '40', 'reducing_schedule': None, 'manufacturing_process': 'smls', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 1.0, 'original_text': '6" SCH 40 A106B SMLS'}
complete:  894 {'category': 'pipe', 'type': 'seamless_pipe', 'primary_size': 14, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'SA-106', 'material_grade': 'B', 'pressure_class': None, 'primary_schedule': 'S100', 'reducing_schedule': None, 'manufacturing_process': 'seamless', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '12700363-PIPE,SMLS,14,S100-SA-106B'}
complete:  1126 {'category': 'flange', 'type': 'socket_weld', 'primary_size': 1.0, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A105', 'material_grade': None, 'pressure_class': '300', 'primary_schedule': '80', 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': 'raised_face', 'end_connections': 'socket_weld', 'trim': None, 'miscellaneous': 'bore', 'confidence': 0.9, 'original_text': '1" 300 RFSW FLANGE S/80 BORE A/SA105'}
complete:  22 {'category': 'fitting', 'type': 'eccentric_reducer', 'primary_size': 8, 'reducing_size': 6, 'length': None, 'material_name': 'stainless_steel', 'material_specification': 'A403', 'material_grade': None, 'pressure_class': None, 'primary_schedule': '10S', 'reducing_schedule': '10S', 'manufacturing_process': None, 'end_finish': None, 'end_connections': 'BW', 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '887520 RED ECC,WELD,8X6*SCH10S/SCH10S,ASTM A403'}
complete:  694 {'category': 'pipe', 'type': 'pipe', 'primary_size': 3.0, 'reducing_size': None, 'length': None, 'material_name': 'stainless_steel', 'material_specification': 'A312', 'material_grade': 'TP304', 'pressure_class': None, 'primary_schedule': '10', 'reducing_schedule': None, 'manufacturing_process': 'smls_or_welded', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': 'SRL', 'confidence': 0.9, 'original_text': '3" S/10 SMLS OR WELDED PIPE X SRL A/SA312-TP304'}
complete:  556 {'category': 'flange', 'type': 'weld_neck', 'primary_size': 4, 'reducing_size': None, 'length': None, 'material_name': None, 'material_specification': None, 'material_grade': None, 'pressure_class': '300', 'primary_schedule': 'STD', 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': 'raised_face', 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '4-300RFWNS-FLG,WN,RF,4,300 ,STD (S40)'}
complete:  642 {'category': 'pipe', 'type': 'seamless_pipe', 'primary_size': 3, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A106', 'material_grade': 'B', 'pressure_class': None, 'primary_schedule': '80', 'reducing_schedule': None, 'manufacturing_process': 'seamless', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '3-XA106BS-PIPE,SMLS,3,XH(S80)-SA-106B'}
complete:  548 {'category': 'flange', 'type': 'blind', 'primary_size': 4.0, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A105', 'material_grade': None, 'pressure_class': '600', 'primary_schedule': None, 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '4" 600 A-105 BLIND'}
complete:  664 {'category': 'pipe', 'type': 'pipe', 'primary_size': 3.0, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A106', 'material_grade': 'B', 'pressure_class': None, 'primary_schedule': 'standard', 'reducing_schedule': None, 'manufacturing_process': 'scarfed', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': 'scarfed to suit 3" NPS OD', 'confidence': 0.9, 'original_text': '3" SCH. STD. PIPE SCARFED TO SUIT 3" NPS OD A106 GR. B'}
complete:  942 {'category': 'pipe', 'type': 'smls', 'primary_size': 1.5, 'reducing_size': None, 'length': None, 'material_name': None, 'material_specification': None, 'material_grade': None, 'pressure_class': None, 'primary_schedule': '160', 'reducing_schedule': None, 'manufacturing_process': 'seamless', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.7, 'original_text': '1-.5-160-PIPE,SMLS,1.5,S160'}
complete:  634 {'category': 'pipe', 'type': 'seamless_pipe', 'primary_size': 3.0, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A53/A106', 'material_grade': 'B', 'pressure_class': None, 'primary_schedule': '160', 'reducing_schedule': None, 'manufacturing_process': 'seamless', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': 'SRL', 'confidence': 0.9, 'original_text': '3" - SCH 160 A53 - B - A106B SMLS- SRL PIPE'}
complete:  154 {'category': 'flange', 'type': 'weld_neck', 'primary_size': 8, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A105', 'material_grade': 'N', 'pressure_class': '300', 'primary_schedule': 'XH', 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': 'raised_face', 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '11100825-FLG,WN,RF,8,300 ,XH (S80)-SA-105N'}
complete:  958 {'category': 'pipe', 'type': 'seamless', 'primary_size': 10, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'SA-106', 'material_grade': 'B', 'pressure_class': None, 'primary_schedule': 'XH', 'reducing_schedule': None, 'manufacturing_process': 'seamless', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '12700315-PIPE,SMLS,10,XH (S60)-SA-106B'}
complete:  156 {'category': 'flange', 'type': 'weld_neck', 'primary_size': 8, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A105', 'material_grade': 'N', 'pressure_class': '300', 'primary_schedule': None, 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': 'raised_face', 'end_connections': None, 'trim': None, 'miscellaneous': 'S100', 'confidence': 1.0, 'original_text': '11101079-FLG,WN,RF,8,300 ,S100-SA-105N'}
complete:  820 {'category': 'flange', 'type': 'weld_neck', 'primary_size': 2, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A105', 'material_grade': 'N', 'pressure_class': '600', 'primary_schedule': '160', 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': 'raised_face', 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 1.0, 'original_text': '11100639-FLG,WN,RF,2,600 ,S160-SA-105N'}
complete:  758 {'category': 'pipe', 'type': 'seamless_pipe', 'primary_size': 20, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A106', 'material_grade': 'B', 'pressure_class': None, 'primary_schedule': '80', 'reducing_schedule': None, 'manufacturing_process': 'seamless', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '12700464-PIPE,SMLS,20,S80-SA-106B'}
complete:  226 {'category': 'fitting', 'type': '90_degree_long_radius_elbow', 'primary_size': 6, 'reducing_size': None, 'length': None, 'material_name': 'stainless_steel', 'material_specification': 'ASTM A403', 'material_grade': 'WP1.0L', 'pressure_class': None, 'primary_schedule': '40S', 'reducing_schedule': None, 'manufacturing_process': 'WLD', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': 'H31943 EL6,90,LR,WLD,S40S,ASTM A403 GRWP1.0L'}
complete:  902 {'category': 'pipe', 'type': 'seamless', 'primary_size': 12, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A106', 'material_grade': 'B', 'pressure_class': None, 'primary_schedule': 'extra_heavy', 'reducing_schedule': None, 'manufacturing_process': 'seamless', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '12700335-PIPE,SMLS,12,XH-SA-106B'}
complete:  338 {'category': 'flange', 'type': 'weld_neck', 'primary_size': 6, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A105', 'material_grade': None, 'pressure_class': '300', 'primary_schedule': 'XXH', 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': 'raised_face', 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 1.0, 'original_text': '11100817-FLG,WN,RF,6,300 ,XXH-SA-105'}
complete:  580 {'category': 'fitting', 'type': 'threadolet', 'primary_size': 8, 'reducing_size': 0.5, 'length': None, 'material_name': 'stainless_steel', 'material_specification': 'A182', 'material_grade': 'F1.0L', 'pressure_class': '3000', 'primary_schedule': None, 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': None, 'end_connections': 'threaded', 'trim': None, 'miscellaneous': 'MSS SP-97', 'confidence': 0.9, 'original_text': 'XF0748 TOL,8X.5,CL3000,MSS SP-97,ASTM A182 GR.F1.0L'}
complete:  552 {'category': 'flange', 'type': 'blind', 'primary_size': 4, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A105', 'material_grade': None, 'pressure_class': '600', 'primary_schedule': None, 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '4" 600 A-105 BLIND'}
complete:  918 {'category': 'pipe', 'type': 'seamless', 'primary_size': 1.5, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A106', 'material_grade': 'B', 'pressure_class': None, 'primary_schedule': 'XXH', 'reducing_schedule': None, 'manufacturing_process': 'SMLS', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '1-.5-XXA106BS-PIPE,SMLS,1.5,XXH'}
complete:  522 {'category': 'flange', 'type': 'weld_neck', 'primary_size': 4, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A105', 'material_grade': 'N', 'pressure_class': '600', 'primary_schedule': 'XXH', 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': 'raised_face', 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 1.0, 'original_text': '11100758-FLG,WN,RF,4,600 ,XXH-SA105N'}
complete:  612 {'category': 'fitting', 'type': 'threaded_plug', 'primary_size': 0.75, 'reducing_size': None, 'length': None, 'material_name': 'stainless_steel', 'material_specification': 'A182', 'material_grade': 'F1.0L', 'pressure_class': None, 'primary_schedule': None, 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': 'round_head', 'end_connections': 'THD', 'trim': None, 'miscellaneous': None, 'confidence': 0.8, 'original_text': 'HL6846 ROUND HEAD PLUG,NPT .75,ASTM A182 GR F1.0L'}
complete:  112 {'category': 'pipe', 'type': 'pipe', 'primary_size': 8, 'reducing_size': None, 'length': 10, 'material_name': 'stainless_steel', 'material_specification': 'A312', 'material_grade': 'TP304L', 'pressure_class': None, 'primary_schedule': None, 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '887483 PI8-10S,ASTM,A312,TP304L'}
complete:  472 {'category': 'fitting', 'type': 'long_radius_90_elbow', 'primary_size': 4, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A234', 'material_grade': 'WPB', 'pressure_class': None, 'primary_schedule': '160', 'reducing_schedule': None, 'manufacturing_process': None, 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '15000391-ELBOW,LR90,4,S160-SA-234-WPB'}
complete:  734 {'category': 'pipe', 'type': 'seamless', 'primary_size': 24, 'reducing_size': None, 'length': None, 'material_name': 'carbon_steel', 'material_specification': 'A106', 'material_grade': 'C', 'pressure_class': None, 'primary_schedule': 'S30', 'reducing_schedule': None, 'manufacturing_process': 'seamless', 'end_finish': None, 'end_connections': None, 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': '12700487-PIPE,SMLS,24,S30 GR C-SA-106C'}
complete:  214 {'category': 'fitting', 'type': 'eccentric_reducer', 'primary_size': 6.0, 'reducing_size': 4.0, 'length': None, 'material_name': 'stainless_steel', 'material_specification': 'A403', 'material_grade': None, 'pressure_class': None, 'primary_schedule': '40S', 'reducing_schedule': '40S', 'manufacturing_process': 'welded', 'end_finish': None, 'end_connections': 'BW', 'trim': None, 'miscellaneous': None, 'confidence': 0.9, 'original_text': 'H31984 RED ECC.-WELD.6X4*SCH40S/SCH40S,ASTM A403'}

In [15]:
df_out.to_csv('Matsco_GT_100_parsed.csv')

In [16]:
df_out

,i,start_time,gt_desc,inc_rfq_raw,inc_rfq,category,type,primary_size,reducing_size,length,...,pressure_class,primary_schedule,reducing_schedule,manufacturing_process,end_finish,end_connections,None,miscellaneous,confidence,original_text
0,418,730.667175,"4"" x 3"" STD CONCENTRIC WELD REDUCER, SA234-WPB","3"" X 4"" Sch. Std Wall Concentric Reducer A234 ...","3"" X 4"" SCH. STD WALL CONCENTRIC REDUCER A234 ...",fitting,concentric_reducer,3.0,4.0,NaN,...,None,standard,None,None,None,None,None,None,0.9,"3"" X 4"" SCH. STD WALL CONCENTRIC REDUCER A234 ..."
1,912,735.859633,"12"" 150# RF WELD NECK FLANGE XH BORE, SA105N","11100566-FLG,WN,RF,12,150#,XH-SA-105N","11100566-FLG,WN,RF,12,150 ,XH-SA-105N",flange,weld_neck,12.0,NaN,NaN,...,150,XH,None,None,raised_face,None,None,None,1.0,"11100566-FLG,WN,RF,12,150 ,XH-SA-105N"
2,494,739.272758,"4"" S-10 LR 90° WELD ELL, SA403-WP304L","H29984 ELBOW,4"",45-WELDED,LR,BW,S10S,ASTM A403","H29984 ELBOW,4"",45-WELDED,LR,BW,S10S,ASTM A403",fitting,45_degree_long_radius_elbow,4.0,NaN,NaN,...,None,None,None,welded,None,butt_weld,None,None,0.9,"H29984 ELBOW,4"",45-WELDED,LR,BW,S10S,ASTM A403"
3,1008,742.778218,"10"" 150# RF WELD NECK FLANGE STD BORE, SA105N-FGP","10-150-FLG,WN,RF,10,150#,STD-SA-105","10-150-FLG,WN,RF,10,150 ,STD-SA-105",flange,weld_neck,10.0,NaN,NaN,...,150,standard,None,None,raised_face,None,None,None,0.9,"10-150-FLG,WN,RF,10,150 ,STD-SA-105"
4,1134,747.890143,"1"" 150# RF SOCKET WELD FLANGE XH BORE, SA105","HB5023 FL1,150,SW,RF,SCHXS,ASTM A105N","HB5023 FL1,150,SW,RF,SCHXS,ASTM A105N",flange,slip_on,1.0,NaN,NaN,...,150,XS,None,None,raised_face,socket_weld,None,None,0.9,"HB5023 FL1,150,SW,RF,SCHXS,ASTM A105N"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,10,1195.433771,"8"" XH .500w BLK QUAD STENCILED SA106-B SEAMLES...","8-XA106BS-PIPE,SMLS,8,XH (S80)","8-XA106BS-PIPE,SMLS,8,XH (S80)",pipe,smls_pipe,8.0,NaN,NaN,...,None,XH,None,seamless,None,None,None,S80,0.9,"8-XA106BS-PIPE,SMLS,8,XH (S80)"
96,124,1200.952696,"8"" 600# RF WELD NECK FLANGE S-120 BORE, SA105N...","11100835-FLG,WN,RF,8,600#,S120","11100835-FLG,WN,RF,8,600 ,S120",flange,weld_neck,8.0,NaN,NaN,...,600,None,None,None,raised_face,None,None,None,0.9,"11100835-FLG,WN,RF,8,600 ,S120"
97,784,1204.929947,"2"" XXH LR 90° WELD ELL, SA234-WPB","2"" XXS LR WN 90 DEG. A234WPB","2"" XXS LR WN 90 DEG. A234WPB",fitting,elbow_90_long_radius,2.0,NaN,NaN,...,None,XXS,None,None,None,butt_weld,None,weld_neck,0.9,"2"" XXS LR WN 90 DEG. A234WPB"
98,1102,1209.000317,"1"" S-160 .250W BLK SA106-B SEAMLESS PIPE","1-160A106BS-PIPE,SMLS,1,S160","1-160A106BS-PIPE,SMLS,1,S160",pipe,seamless_pipe,1.0,NaN,NaN,...,None,160,None,seamless,None,None,None,None,0.9,"1-160A106BS-PIPE,SMLS,1,S160"
99,990,1215.464853,"10"" S-160 1.125WA53/SA106-B SMLS PIPE","12700321-PIPE,SMLS,10,S160-SA-106B","12700321-PIPE,SMLS,10,S160-SA-106B",pipe,seamless,10.0,NaN,NaN,...,None,160,None,seamless,None,None,None,None,0.9,"12700321-PIPE,SMLS,10,S160-SA-106B"

In [17]:
df_out.columns

Index([                     'i',             'start_time',
                      'gt_desc',            'inc_rfq_raw',
                      'inc_rfq',               'category',
                         'type',           'primary_size',
                'reducing_size',                 'length',
                'material_name', 'material_specification',
               'material_grade',         'pressure_class',
             'primary_schedule',      'reducing_schedule',
        'manufacturing_process',             'end_finish',
              'end_connections',                     None,
                'miscellaneous',             'confidence',
                'original_text'],
      dtype='object')

In [18]:
final_df_new.columns

Index(['Customer's Inbound RFQ Description', 'Selected Part Number',
       'Descrip from Prod Cat', 'Product Code', 'Description', 'Category_GT',
       'Type_GT', 'Primary Size_GT', 'Reducing Size_GT', 'Length_GT',
       'Material Name_GT', 'Material Specification_GT', 'Material Grade_GT',
       'Pressure Class_GT', 'Primary Schedule_GT', 'Reducing Schedule_GT',
       'Manufacturing Process_GT', 'End Finish_GT', 'End Connections_GT',
       'Trim_GT', 'Miscellaneous_GT', 'confidence_GT', 'original_text_GT',
       'Primary Wall_GT', 'Reducing Wall_GT', 'Wall Thickness_GT', 'max_GT',
       'od_GT', 'id_GT', 'wall_GT'],
      dtype='object')

In [19]:
print(len(df_out))
print(len(final_df_new))

100
100

In [ ]:
# final_df_new
#
# Index(['Customer's Inbound RFQ Description', 'Selected Part Number',
#        'Descrip from Prod Cat', 'Product Code', 'Description', 'Category_GT',
#        'Type_GT', 'Primary Size_GT', 'Reducing Size_GT', 'Length_GT',
#        'Material Name_GT', 'Material Specification_GT', 'Material Grade_GT',
#        'Pressure Class_GT', 'Primary Schedule_GT', 'Reducing Schedule_GT',
#        'Manufacturing Process_GT', 'End Finish_GT', 'End Connections_GT',
#        'Trim_GT', 'Miscellaneous_GT', 'confidence_GT', 'original_text_GT',
#        'Primary Wall_GT', 'Reducing Wall_GT', 'Wall Thickness_GT', 'max_GT',
#        'od_GT', 'id_GT', 'wall_GT'],
#       dtype='object')

In [29]:

rfq_suffix_cols = ['start_time','category','type','primary_size','reducing_size','length',
'material_name', 'material_specification',
'material_grade','pressure_class',
'primary_schedule','reducing_schedule',
'manufacturing_process','end_finish',
'end_connections',
'miscellaneous','confidence',
'original_text']


df_out_new = df_out.rename(columns={col: f"{col.upper()}_RFQ" for col in rfq_suffix_cols})


merged_df = final_df_new.merge(df_out_new, left_index=True, right_on='i')
merged_df

,Customer's Inbound RFQ Description,Selected Part Number,Descrip from Prod Cat,Product Code,Description,Category_GT,Type_GT,Primary Size_GT,Reducing Size_GT,Length_GT,...,PRESSURE_CLASS_RFQ,PRIMARY_SCHEDULE_RFQ,REDUCING_SCHEDULE_RFQ,MANUFACTURING_PROCESS_RFQ,END_FINISH_RFQ,END_CONNECTIONS_RFQ,None,MISCELLANEOUS_RFQ,CONFIDENCE_RFQ,ORIGINAL_TEXT_RFQ
0,"3"" X 4"" Sch. Std Wall Concentric Reducer A234 ...",KWCO040030SSKB,"4"" x 3"" STD CONCENTRIC WELD REDUCER, SA234-WPB",KWCO040030SSKB,"4"" x 3"" STD CONCENTRIC WELD REDUCER, SA234-WPB",FITTING,CONCENTRIC REDUCER,4.0,3,NaN,...,None,standard,None,None,None,None,None,None,0.9,"3"" X 4"" SCH. STD WALL CONCENTRIC REDUCER A234 ..."
1,"11100566-FLG,WN,RF,12,150#,XH-SA-105N",IFWN011201XNA,"12"" 150# RF WELD NECK FLANGE XH BORE, SA105N",IFWN011201XNA,"12"" 150# RF WELD NECK FLANGE XH BORE, SA105N",FLANGE,WELD NECK,12.0,NaN,NaN,...,150,XH,None,None,raised_face,None,None,None,1.0,"11100566-FLG,WN,RF,12,150 ,XH-SA-105N"
2,"H29984 ELBOW,4"",45-WELDED,LR,BW,S10S,ASTM A403",IWL9404001,"4"" S-10 LR 90° WELD ELL, SA403-WP304L",IWL9404001,"4"" S-10 LR 90° WELD ELL, SA403-WP304L",FITTING,ELBOW 90 LONG RADIUS,4.0,NaN,NaN,...,None,None,None,welded,None,butt_weld,None,None,0.9,"H29984 ELBOW,4"",45-WELDED,LR,BW,S10S,ASTM A403"
3,"10-150-FLG,WN,RF,10,150#,STD-SA-105",FWN011001S,"10"" 150# RF WELD NECK FLANGE STD BORE, SA105N-FGP",FWN011001S,"10"" 150# RF WELD NECK FLANGE STD BORE, SA105N-FGP",FLANGE,WELD NECK,10.0,NaN,NaN,...,150,standard,None,None,raised_face,None,None,None,0.9,"10-150-FLG,WN,RF,10,150 ,STD-SA-105"
4,"HB5023 FL1,150,SW,RF,SCHXS,ASTM A105N",IFSW010101X,"1"" 150# RF SOCKET WELD FLANGE XH BORE, SA105",IFSW010101X,"1"" 150# RF SOCKET WELD FLANGE XH BORE, SA105",FLANGE,SOCKET WELD,1.0,NaN,NaN,...,150,XS,None,None,raised_face,socket_weld,None,None,0.9,"HB5023 FL1,150,SW,RF,SCHXS,ASTM A105N"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,"8-XA106BS-PIPE,SMLS,8,XH (S80)",PA080XH,"8"" XH .500w BLK QUAD STENCILED SA106-B SEAMLES...",PA080XH,"8"" XH .500w BLK QUAD STENCILED SA106-B SEAMLES...",PIPE,SEAMLESS,8.0,NaN,NaN,...,None,XH,None,seamless,None,None,None,S80,0.9,"8-XA106BS-PIPE,SMLS,8,XH (S80)"
96,"11100835-FLG,WN,RF,8,600#,S120",FWN06080112,"8"" 600# RF WELD NECK FLANGE S-120 BORE, SA105N...",FWN06080112,"8"" 600# RF WELD NECK FLANGE S-120 BORE, SA105N...",FLANGE,WELD NECK,8.0,NaN,NaN,...,600,None,None,None,raised_face,None,None,None,0.9,"11100835-FLG,WN,RF,8,600 ,S120"
97,"2"" XXS LR WN 90 DEG. A234WPB",KWL9020XX,"2"" XXH LR 90° WELD ELL, SA234-WPB",KWL9020XX,"2"" XXH LR 90° WELD ELL, SA234-WPB",FITTING,LONG RADIUS 90 ELBOW,2.0,NaN,NaN,...,None,XXS,None,None,None,butt_weld,None,weld_neck,0.9,"2"" XXS LR WN 90 DEG. A234WPB"
98,"1-160A106BS-PIPE,SMLS,1,S160",IPA01016K,"1"" S-160 .250W BLK SA106-B SEAMLESS PIPE",IPA01016K,"1"" S-160 .250W BLK SA106-B SEAMLESS PIPE",PIPE,SEAMLESS,1.0,NaN,NaN,...,None,160,None,seamless,None,None,None,None,0.9,"1-160A106BS-PIPE,SMLS,1,S160"
99,"12700321-PIPE,SMLS,10,S160-SA-106B",IPA10016TM,"10"" S-160 1.125WA53/SA106-B SMLS PIPE",IPA10016TM,"10"" S-160 1.125WA53/SA106-B SMLS PIPE",PIPE,SMLS PIPE,10.0,NaN,NaN,...,None,160,None,seamless,None,None,None,None,0.9,"12700321-PIPE,SMLS,10,S160-SA-106B"

In [33]:
merged_df.columns
merged_df.to_csv('MATSCO_GT_100_PARSED_RFQS.CSV',index=False)